In [1]:
import torch
import numpy as np
torch.__version__

'1.10.2+cu113'

### Tensor
张量是一个统称，其中包含很多类型：是一个可以包含高维数据的统称的一个数据结构（类型）

1. 0阶张量：标量, scaler、常数，0-D Tensor . 在计算loss中, 返回的就是一个标量.

2. 1阶张量：向量 vector，1-D Tensor 

3. 2阶张量：矩阵 matrix，2-D Tensor

4. 3阶张量

5. ...

6. N阶张量

   这个阶也称之为维度, 即shape个数.

In [2]:
# 在python中创建Tensor
# 首先要区分的是torch.Tensor() 和 torch.tensor()
# 首先大写的Tensoe是类, 一般来说是传入形状然后生成未初始化的tensor. 我们可以通过类直接创建不同类型的tensor
# 而小的的tensor是方法, 一般来说是传入数据, 直接生成tensor. 我们可以指定dtype来控制数据类型
# 接下来我们就使用torch中的方法创建tensor

In [3]:
# 使用python中的list创建tensor
t1 = torch.tensor([[1, 3], [1, 4]])
t1.dtype # torch.int64
t1
# tensor([[1, 3],
        # [1, 4]])
        


tensor([[1, 3],
        [1, 4]])

In [4]:
#  使用数据直接创建tensor
torch.tensor(np.array(
    [[1, 2, 3],  
     [4, 5, 6]],
     dtype=np.float64 # 在np中指定dtype类型
)) # 那么生成的tensor类型也是与np类型相同的


tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [5]:
# 使用Torch的API创建tensor：
# 1. 创建一个空的tenosr变量, 未初始化, 会用无用数据进行填充
torch.empty([4, 3])

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.8026e-45, 0.0000e+00],
        [1.1210e-44, 0.0000e+00, 1.4013e-45],
        [0.0000e+00, 0.0000e+00, 1.0469e-38]])

In [6]:
# 创建全为1 的tensor
torch.ones([4, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [7]:
# 创建全为0的tensor
torch.zeros([4, 5])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
# 指定数值创建:
# 例子: 创建一个4*5的矩阵, 并全部用10进行填充
torch.full([4 ,5],10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

In [9]:
# 随机创建_创建一个矩阵, 符合均匀分布, 范围: [0, 1)
torch.rand(size=(4, 3))
# 如果要创建到固定范围内: [a, b)
a = 5
b = 10

(b-a) * torch.rand(size=(4, 3)) + a

tensor([[6.8679, 6.0127, 7.9359],
        [5.6682, 5.2238, 9.7485],
        [9.7179, 9.8773, 7.2079],
        [7.8719, 6.3506, 6.0374]])

In [10]:
# 创建随机整数:
# 创建整数, 同样符合均匀分布
torch.randint(low=3, high=10, size=(4, 6))

tensor([[6, 5, 4, 8, 5, 9],
        [6, 7, 4, 6, 7, 8],
        [7, 7, 6, 4, 7, 8],
        [6, 7, 3, 6, 5, 4]])

In [11]:
# 创建随机tensor, 符合标准正态分布:
torch.randn(size=(4, 3))

tensor([[-1.1252, -0.7768, -0.8509],
        [-0.5744,  0.2997,  0.5756],
        [ 0.1134, -0.9553,  0.1004],
        [-1.0517,  2.0844,  2.5523]])

In [12]:
# 也可以让每个元素, 都服从不同的正太分布:
torch.normal(
    mean=torch.full(size=(10, 1), fill_value=10.),
    std=torch.full(size=(10,1), fill_value=4.0)
)
# 注意, 必须是类型是一样的,并且大小也要是一样的.
# 可以都指定为Float

tensor([[11.1677],
        [ 8.0804],
        [12.2535],
        [13.4908],
        [10.5689],
        [10.2360],
        [14.0248],
        [ 2.9045],
        [10.2188],
        [ 2.4084]])

### tensor的常用方法

In [13]:
# 当tensor中只有一个元素的时候, 我们可以直接使用该方法获取其中的元素值
# 不用在一层一层索引了
t2 = torch.tensor([[1]], dtype=torch.float32)
t2 # 此时如果我们需要取出里面的值我们需要一层一层索引:

tensor([[1.]])

In [14]:
t2[0][0]

tensor(1.)

In [15]:
# 但是我们可以直接使用: item()就直接可以得到其中的元素值
t2.item()

1.0

In [16]:
# 转换为numpy数组
t3 = torch.randn(size=(3, 4))
t3

tensor([[ 0.1698, -1.4021,  0.8972, -0.9803],
        [ 0.1119, -1.0663,  1.8746, -0.0616],
        [ 1.0974,  1.2527, -0.4841,  0.1457]])

In [17]:
print("t3.numpy():",t3.numpy()) # 直接从tensor 转换到 ndarray
print(type(t3.numpy())) # 直接就是原地修改了。


t3.numpy(): [[ 0.16983157 -1.4021273   0.8972213  -0.9803232 ]
 [ 0.11193099 -1.0662715   1.874605   -0.06164317]
 [ 1.0973673   1.2527341  -0.4841227   0.14570478]]
<class 'numpy.ndarray'>


In [53]:
# 获取形状
t4 = torch.Tensor(size=(10, 20))
t4.size()

torch.Size([10, 20])

In [67]:
# 类型的变换:
print(t4.double().dtype)
t4 = t4.double() # 但是类型的修改不是原地修改, 所以我们需要再赋值
t4.dtype #

torch.float64


torch.float64

In [61]:
# tensor的其他操作
# torch.*_like(A) # 创建一个与A形状相同的一个tensor对象
# 例如:
t4_like = torch.ones_like(t4)
t4_like # 就是创建一个与t4形状相同的全1 矩阵

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])

In [71]:
# tensor.new_*(A) # 用于创建一个与A同类型的的tensor对象
t4.new_ones(size=(5,3), dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [74]:
# tensor的其他操作.
# tensor和tensor相加:
a = torch.DoubleTensor(size=(4, 3))
b = torch.randn_like(a)
print(a)
print(b) # 创建了和a一样size和dtype的tensor


tensor([[6.9525e-310, 6.9525e-310, 6.9525e-310],
        [6.9525e-310, 6.9525e-310, 6.9525e-310],
        [6.9525e-310, 6.9525e-310, 6.9525e-310],
        [6.9525e-310, 6.9525e-310, 6.9525e-310]], dtype=torch.float64)
tensor([[ 1.0649, -1.5081,  1.6303],
        [ 0.6871,  1.0619, -0.0838],
        [ 1.8371, -1.7209,  1.0924],
        [-0.8186,  0.4940, -0.0023]], dtype=torch.float64)
