In [1]:
import torch


In [4]:
# 生成一个符合正态分布的随机数矩阵, 矩阵大小(2, 3)
a = torch.randn(2, 3)
a # 这也是动态图的优点, 直接运行

tensor([[-1.4465,  0.2991, -0.7022],
        [ 1.3699,  0.3138, -0.3262]])

In [5]:
a.type()

'torch.FloatTensor'

In [7]:
type(a) # 只打印出一个基本的信息

torch.Tensor

In [9]:
isinstance(a,torch.FloatTensor) # 用来做检验

True

In [12]:
isinstance(a, torch.cuda.FloatTensor) # False

False

In [14]:
# 此时我们可以将数据转换
# 从CPU -> GPU:
a_gpu = a.cuda() # 返回一个GPU上面的引用
isinstance(a_gpu, torch.cuda.FloatTensor) # 

True

In [17]:
b = torch.tensor(10.0)
b

tensor(10.)

In [20]:
# 属性:
b.shape # torch.Size([])
# 是一个空list的size

torch.Size([])

In [28]:
# 计算维度:
len(b.shape)
b.dim()

0

In [27]:
# 注意, size()是方法, 不是属性 
b.size()


torch.Size([])

In [31]:
# 创建一阶Tensor
a = torch.ones(2)
a # tensor([1., 1.])

tensor([1., 1.])

In [32]:
a.shape # torch.Size([2])

torch.Size([2])

In [39]:
a.size()

torch.Size([2])

In [40]:
# Dim 2, 二阶张量
a = torch.randn(2, 3)
a

tensor([[-1.7881,  0.8048, -1.3497],
        [ 0.5926,  0.3034, -2.2694]])

In [41]:
a.shape

torch.Size([2, 3])

In [46]:
a.size(1) # 通过索引获取对应维度的值

3

In [48]:
a.shape[1] # 注意这里shape是索引[] 

3

In [50]:
# 创建三维Tensor
a = torch.rand(1, 2, 3)
a

tensor([[[0.0647, 0.6055, 0.7591],
         [0.5759, 0.9538, 0.5353]]])

In [51]:
a.shape

torch.Size([1, 2, 3])

In [53]:
a[0] # 取出第一个维度

tensor([[0.0647, 0.6055, 0.7591],
        [0.5759, 0.9538, 0.5353]])

In [54]:
list(a.shape)
# 这样可以将size类型转换为list类型


[1, 2, 3]

In [56]:
# 创建四阶张量
a = torch.rand(2, 3, 28, 28)
a

tensor([[[[0.8210, 0.5992, 0.9582,  ..., 0.9232, 0.8171, 0.0424],
          [0.7305, 0.0583, 0.4450,  ..., 0.6454, 0.0126, 0.6548],
          [0.1072, 0.7661, 0.4749,  ..., 0.3411, 0.2497, 0.7363],
          ...,
          [0.3627, 0.3750, 0.4811,  ..., 0.5490, 0.7321, 0.2644],
          [0.8853, 0.5905, 0.1615,  ..., 0.5665, 0.4945, 0.1020],
          [0.2686, 0.0613, 0.9400,  ..., 0.8664, 0.9799, 0.1032]],

         [[0.0699, 0.9441, 0.5132,  ..., 0.1213, 0.5312, 0.7838],
          [0.7960, 0.0149, 0.9131,  ..., 0.0479, 0.9470, 0.1359],
          [0.3696, 0.6634, 0.1975,  ..., 0.5772, 0.5867, 0.3704],
          ...,
          [0.5296, 0.1282, 0.4126,  ..., 0.8862, 0.6103, 0.5560],
          [0.1058, 0.3310, 0.4927,  ..., 0.0615, 0.4394, 0.1574],
          [0.8211, 0.8111, 0.5772,  ..., 0.6857, 0.7561, 0.4820]],

         [[0.4468, 0.4589, 0.6212,  ..., 0.2372, 0.3656, 0.2101],
          [0.9508, 0.6042, 0.7255,  ..., 0.7208, 0.7605, 0.4060],
          [0.2652, 0.5197, 0.5923,  ..., 0

In [57]:
a.shape

torch.Size([2, 3, 28, 28])

In [58]:
a.numel() # 2*3*28*28


4704